services:
  - type: web
    name: majt-shop
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_UTILISATEUR
        value: admin
      - key: ADMIN_MOT_DE_PASSE
        sync: false
      - key: FLASK_DEBUG
        value: "0"
      - key: MYSQL_HOTE
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: MYSQL_UTILISATEUR
        sync: false
      - key: MYSQL_MOT_DE_PASSE
        sync: false
      - key: MYSQL_BASE
        sync: false
